"""
prompts package — re-exports everything so existing `from prompts import X` calls still work.
"""

from .narrator import NARRATOR_SYSTEM_PROMPT, OPENING_SCENE_PROMPT, RECAP_SCENE_PROMPT
from .structured import SUMMARY_PROMPT, WORLD_UPDATE_PROMPT, RESOURCE_UPDATE_PROMPT
from .context import build_context
from game_data import (
    ANCESTRIES,
    CLASSES,
    ANCESTRY_ABILITY_BOOSTS,
    CLASS_KEY_ABILITY,
    CLASS_SECONDARY_ABILITIES,
    XP_PER_LEVEL,
    CLASS_STARTING_GOLD,
    CLASS_HP_PER_LEVEL,
    CLASS_STARTING_GEAR,
    CLASS_SPELL_SLOTS,
    CLASS_FOCUS_POINTS,
    ADVENTURE_STARTERS,
)

__all__ = [
    "NARRATOR_SYSTEM_PROMPT", "OPENING_SCENE_PROMPT", "RECAP_SCENE_PROMPT",
    "SUMMARY_PROMPT", "WORLD_UPDATE_PROMPT", "RESOURCE_UPDATE_PROMPT",
    "build_context",
    "ANCESTRIES", "CLASSES", "ANCESTRY_ABILITY_BOOSTS", "CLASS_KEY_ABILITY",
    "CLASS_SECONDARY_ABILITIES", "XP_PER_LEVEL", "CLASS_STARTING_GOLD",
    "CLASS_HP_PER_LEVEL", "CLASS_STARTING_GEAR", "CLASS_SPELL_SLOTS",
    "CLASS_FOCUS_POINTS", "ADVENTURE_STARTERS",
]
